build: Fix a build error by adding -std=c++11
Since cgdb uses some C++11 syntax, it'd be better to set the C++
standard explicitly.

This patch is to fix the below compilation error.

  make[3]: Entering directory '/home/honggyu/src/cgdb/lib/kui'
  g++ -DHAVE_CONFIG_H -I. -I../..    -I../../lib/util -g -O2 -MT kui.o -MD -MP -MF .deps/kui.Tpo -c -o kui.o kui.cpp
  kui.cpp: In function ‘int kui_ms_destroy(kui_map_set*)’:
  kui.cpp:310:15: error: ‘it’ does not name a type
       for (auto it = kui_ms->maps.cbegin(); it != kui_ms->maps.cend();)
                 ^
  kui.cpp:310:43: error: expected ‘;’ before ‘it’
       for (auto it = kui_ms->maps.cbegin(); it != kui_ms->maps.cend();)
                                             ^

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>