build: Add explict include to avoid build error
This patch is to avoid the following compilation error.

  cgdb/lib/util/pseudo.cpp:203: error: undefined reference to 'openpty'

Since 'openpty' requires 'utmp.h', it'd be better to include it
explicitly.  This error was found when trying cross compilation.

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>